<a href="https://colab.research.google.com/github/DrCybernotix/DeepLearning-Tensorflow/blob/main/playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
any = tf.constant(9)
any.shape

TensorShape([])

In [ ]:
any.ndim

0

In [ ]:
some_vec = tf.constant([11,3,33,7])
some_vec
#some_vec.ndim

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11,  3, 33,  7], dtype=int32)>

In [ ]:
some_vec.shape

TensorShape([4])

In [ ]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3,1],
                       [4, 5, 6,1]],
                      [[7, 8, 9,1],
                       [10, 11, 12,1]],
                      [[13, 14, 15,1],
                       [16, 17, 18,1]],
                      [[7, 8, 9,1],
                       [10,11, 12,1]],
                      [[1, 2, 3,1],
                       [4, 5, 6,1]]])
tensor

<tf.Tensor: shape=(5, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  1],
        [ 4,  5,  6,  1]],

       [[ 7,  8,  9,  1],
        [10, 11, 12,  1]],

       [[13, 14, 15,  1],
        [16, 17, 18,  1]],

       [[ 7,  8,  9,  1],
        [10, 11, 12,  1]],

       [[ 1,  2,  3,  1],
        [ 4,  5,  6,  1]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
## number of entities   number of dimensions of each entity   number of elements in each entity

In [ ]:
changeable = tf.Variable([10,11,12])
changeable

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 11, 12], dtype=int32)>

In [ ]:
changeable[2].assign(99)
changeable

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 11, 99], dtype=int32)>

In [ ]:
#creating two random but same tensors using same seed size ofc

rnd1 = tf.random.Generator.from_seed(22)
rnd1 = rnd1.normal(shape=(3,2))
rnd1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7531523 ,  2.0261486 ],
       [-0.06997604,  0.85445154],
       [ 0.1175475 ,  0.03493892]], dtype=float32)>

In [ ]:
rnd2 = tf.random.Generator.from_seed(22)
rnd2 = rnd2.normal(shape=(4,4))
rnd2

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.7531523 ,  2.0261486 , -0.06997604,  0.85445154],
       [ 0.1175475 ,  0.03493892, -1.5700307 ,  0.44575813],
       [ 0.10944034, -0.8035768 , -1.7166729 ,  0.3738578 ],
       [-0.14371012, -0.34646833,  1.1456194 , -0.416     ]],
      dtype=float32)>

In [ ]:
tf.random.shuffle(rnd1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.06997604,  0.85445154],
       [ 0.1175475 ,  0.03493892],
       [-0.7531523 ,  2.0261486 ]], dtype=float32)>

In [ ]:
experiment = tf.zeros([1,2,2,6])
experiment

<tf.Tensor: shape=(1, 2, 2, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
new_experiment = experiment[..., tf.newaxis]

In [ ]:
new + 69 
#new.numpy()

NameError: ignored

In [ ]:
mul1 = tf.random.Generator.from_seed(69)
mul1 = mul1.normal(shape=(4,2))

mul2 = tf.random.Generator.from_seed(40)
mul2 = mul2.normal(shape=(2,4))


In [ ]:

mul2

In [ ]:
mul1

In [ ]:
tf.matmul(mul1,mul2)  #also equals mul1@mul2 gives same output

In [ ]:
tf.cast(mul1, tf.int32)


In [ ]:
mul1

In [ ]:
we got tf.transpose(bla) and tf.reshape(bla) methods they change the axes but transpose takes tthe transpose and reshape arranegs the entries of the martix in our wanted manner.

In [ ]:
tf.tensordot(mul1, mul2, axes=1)

In [ ]:
import numpy as np

In [ ]:
#create random tensor using numbers between 0 to 100 and size of 50
rand =  tf.constant(np.random.randint(0,100, size = 50))
rand

In [ ]:
tf.reduce_mean(rand)
tf.reduce_sum(rand)
tf.reduce_min(rand
              )
tf.reduce_max(rand)

In [ ]:
tf.reduce_any(rand)

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(rand)

In [ ]:
f = tf.random.normal(shape=[33], dtype = tf.int32)

In [ ]:
f = tf.random.uniform(shape=[33], dtype = tf.int32, maxval=22)

In [ ]:
f

In [ ]:
tf.argmax(f)

In [ ]:
f[tf.argmax(f)]


In [ ]:

tf.squeeze(f) #it removes the 1 i.e single dimension values from out tensro like we saw in tensor.sahpe (1,2,3,1) so after tensor.squeeze it gives output shape as tensor.shape = (2,3)

In [ ]:

tf.one_hot(f, depth = 50)


In [ ]:
gg = tf.random.uniform([3], maxval = 55, dtype = tf.int32)

gg


In [ ]:
tf.one_hot(gg)

In [ ]:
x = tf.one_hot(gg, depth=3, dtype=tf.int32)

In [ ]:
x

In [ ]:
some_list = [1,2,3,4]

In [ ]:
tf.one_hot(some_list, off_value = "content guys", on_value="sheeeeeeesh", depth = 4)

some regression


In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
x =  np.array([3.0,6.8,9.0,5.4,4,2,9.0])
y =  np.array([6.0,4.8,8.0,4.4,2,2,5.0])

In [ ]:
plt.scatter(x,y);

In [ ]:
x = tf.random.normal(shape=[1,1,5], )


In [ ]:
y = tf.random.normal(shape=[1,1,5], )


In [ ]:
plt.scatter(x,y);

In [ ]:
x,y

In [ ]:
house_info = tf.constant(["dub", "dub2", "dub3"])
#house_price = tf.cast(tf.random.normal(shape=(1)), dtype = tf.int32)
house_price = tf.constant([99999])

In [ ]:
input_shape = x.shape
output_shape = y.shape
input_shape, output_shape

In [ ]:
tf.random.set_seed(42)

In [ ]:
model = tf.keras.Sequential(
    [tf.keras.layers.Dense(1)]
    )

In [ ]:
model.compile(loss=tf.keras.losses.mse,
              optimizer = tf.keras.optimizers.SGD(),
              metrics = ["mse"])

In [ ]:
model.fit(x, y, epochs = 6)

In [ ]:
x,y

In [ ]:
model.predict([[[1.0,2.0,3.0,4.0,5.0]]])

In [ ]:
a = tf.constant([1,2,3,4,5,6,7,8])
b = tf.constant([1,4,6,8,10,12,14,16])

In [ ]:
a,b

In [ ]:
#build
modelOrWot = tf.keras.Sequential(
    
    [tf.keras.layers.Dense(1)]
    
)
#compiling
modelOrWot.compile(loss = tf.keras.losses.mae,
              optimizer = tf.keras.optimizers.SGD(),
              metrics = ["mae"])


In [ ]:

#model fitting
modelOrWot.fit(a, b, epochs = 100)


In [ ]:
modelOrWot.predict([11])

In [ ]:
x = tf.range(-100,100,4)
x

In [ ]:
y = x*2
y

In [ ]:
plt.scatter(x,y)

In [ ]:
x_train = x[:40]
y_train = y[:40]

x_test = x[40:]
y_test = y[40:]


In [ ]:
plt.figure(figsize=(10,10))
plt.scatter(x_train,y_train, c= 'r')
plt.scatter(x_test, y_test, c = 'b')
plt.legend();

In [ ]:
newmod = tf.keras.Sequential(
    tf.keras.layers.Dense(5, input_shape=[3])

)


#compiling
#modelOrWot.compile(loss = tf.keras.losses.mae,
#              optimizer = tf.keras.optimizers.SGD(),
#              metrics = ["mae"])

newmod.compile(loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.SGD(),
               metrics = ["mae"]

             )

newmod.summary()

In [ ]:
from tensorflow.keras.utils import plot_model
#plot_model(model=newmod, show_shapes = True)

In [ ]:
#experment experiment experiment 

In [ ]:
x_train = tf.range(-200,200,6)
x_train 
y_train = x_train*2
y_train

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1)]
)

model.compile(loss = tf.keras.losses.mae,
              optimizer = tf.keras.optimizers.SGD(),
              metrics = ["mae"]
              
  )

model.fit(x_train,y_train,epochs = 100)

In [ ]:
varypred = model.predict(x_test)

In [ ]:
import pandas as pd


In [ ]:
import tensorflow as tf
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
insurance =pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")
insurance

In [ ]:
#sheesh

insurance_onehot = pd.get_dummies(insurance)
insurance_onehot

In [ ]:
x = insurance_onehot.drop("charges", axis = 1)
x

In [ ]:
y  = insurance_onehot["charges"]
y

In [ ]:
y.head()

In [ ]:
x.head()

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
trainx, testx, trainy, testy = train_test_split(x,y, test_size = 0.2, random_state = 41)

In [ ]:
tf.random.set_seed(41)

insurance_model = tf.keras.Sequential( [
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)]
)


insurance_model.compile(loss = tf.keras.losses.mae,
                        optimizer = tf.keras.optimizers.Adam(lr = 0.001),
                        metrics = ["mae"])

insurance_model.fit(trainx, trainy, epochs = 100)

In [ ]:
insurance_model.evaluate(testx, testy)

In [ ]:
tf.random.set_seed(44)
insurancemodel2 = tf.keras.Sequential(
    [
     tf.keras.layers.Dense(100),
     tf.keras.layers.Dense(10),
     tf.keras.layers.Dense(1)
    ]
)

insurancemodel2.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.Adam(),
    metrics=["mae"]
)
insurancemodel2.fit(trainx,trainy, epochs = 100)

In [ ]:
insurancemodel2.evaluate(testx, testy)

In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt
import tensorflow as tf

insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")
insurance

In [ ]:
!pip install sklearn

In [ ]:
!pip install MinMaxScalar

In [ ]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

ct = make_column_transformer(
    (MinMaxScaler(),["age", "bmi", "children"]),
    (OneHotEncoder(handle_unknown = "ignore"), ["sex", "smoker", "region"])
  
)

x = insurance.drop("charges", axis = 1)
y = insurance["charges"]  

xtr, xts, ytr, yts = train_test_split(x,y,test_size = 0.2, random_state=42)

ct.fit(xtr)

xtrn = ct.transform(xtr)
xtsn = ct.transform(xts)

In [ ]:
xtrn[0]

In [ ]:
xtrn

In [ ]:
tf.random.set_seed(42)

mod = tf.keras.Sequential(
    [
     tf.keras.layers.Dense(100),
     tf.keras.layers.Dense(10),
     tf.keras.layers.Dense(1)

    ]
)

mod.compile(
    loss = tf.keras.losses.mae,
    optimizer = tf.keras.optimizers.Adam(),
    metrics = ["mae"]
)

mod.fit(xtrn, ytr, epochs = 100, verbose = 1)


In [ ]:
mod.evaluate(xtsn, yts)

In [ ]:
mod.summary()

In [ ]:
from sklearn.datasets import make_circles

nsamples = 1000
x, y = make_circles(nsamples,
                    noise = 0.03,
                    random_state = 41)



In [ ]:
x,y[:10]

In [ ]:
import pandas as pd

circles = pd.DataFrame({"X0":x[:, 0], "X1":x[:, 1], "label":y})
circles

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(x[:,0], x[:, 1], c=y)

In [ ]:
import tensorflow as tf

In [ ]:
binaryCM = tf.keras.Sequential(
    [tf.keras.layers.Dense(4, activation = "relu"),
     tf.keras.layers.Dense(4, activation = "relu"),
     tf.keras.layers.Dense(1, activation = "sigmoid")]
)

In [ ]:
binaryCM.compile(
    loss = tf.keras.losses.binary_crossentropy,
    optimizer = tf.keras.optimizers.Adam(),
    metrics = ["accuracy"]
)

In [ ]:
binaryCM.fit(x, y, epochs = 100)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, random_state =69)

In [ ]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

In [ ]:
binaryCM.fit(xtrain, ytrain)

In [ ]:
binaryCM.evaluate(xtest, ytest)

In [ ]:
history_variable=binaryCM.fit(xtrain, ytrain, epochs = 100, verbose = 0)

In [ ]:
newhistory= history_variable.history

In [ ]:
pd.DataFrame(newhistory)

In [ ]:
pd.DataFrame(history_variable.history).plot()
plt.title("loss curve")

In [ ]:
tf.random.set_seed(42)

In [ ]:
lrexperimentmodel = tf.keras.Sequential(
    [
     tf.keras.layers.Dense(4, activation = "relu"),
     tf.keras.layers.Dense(4, activation = "relu"),
     tf.keras.layers.Dense(1, activation = "sigmoid")
    ]
)

lrexperimentmodel.compile(
    loss = tf.keras.losses.binary_crossentropy,
    optimizer = tf.keras.optimizers.Adam(),
    metrics = ["accuracy"]
)

#now before fitting lets create a learning rate callback

lr_callback = tf.keras.callbacks.LearningRateScheduler( lambda epoch : 1e-4*10**(epoch/20) )


#now go on and fit the model
varforhistory=lrexperimentmodel.fit(
    xtrain,
    ytrain,epochs = 100, 
    callbacks = [lr_callback],
    verbose = 0
)


In [ ]:
pd.DataFrame(varforhistory.history).plot(xlabel = "epochs")

In [ ]:
modelacc = tf.keras.metrics.Accuracy()
modelacc

In [ ]:
accuracy = lrexperimentmodel.evaluate(xtest, ytest)


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
ypred = lrexperimentmodel.evaluate(xtest)

In [ ]:
confusion_matrix(ytest, ypred)

In [ ]:
we've to round values in y pred to eliminate these errors

In [ ]:
tf.round(ypred)[:10]

In [ ]:
confusion_matrix(ytest, tf.round(ypred))

CNN 


In [ ]:
import zipfile

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/food_vision/pizza_steak.zip 

--2021-10-27 07:51:09--  https://storage.googleapis.com/ztm_tf_course/food_vision/pizza_steak.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 209.85.145.128, 172.217.219.128, 209.85.147.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|209.85.145.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 109579078 (105M) [application/zip]
Saving to: ‘pizza_steak.zip’

pizza_steak.zip     100%[===================>] 104.50M   158MB/s    in 0.7s    

2021-10-27 07:51:10 (158 MB/s) - ‘pizza_steak.zip’ saved [109579078/109579078]



In [ ]:
#unzipping

zip_ref = zipfile.ZipFile("pizza_steak.zip", "r")
zip_ref.extractall()
zip_ref.close()

walking throug the data

In [ ]:
import os 
for dirpath, dirnames, filenames in os.walk("pizza_steak"):
  print(f"There are {len(dirnames)} directories and {len(filenames)} images in '{dirpath}'.")

There are 2 directories and 1 images in 'pizza_steak'.
There are 2 directories and 1 images in 'pizza_steak/train'.
There are 0 directories and 750 images in 'pizza_steak/train/steak'.
There are 0 directories and 750 images in 'pizza_steak/train/pizza'.
There are 2 directories and 1 images in 'pizza_steak/test'.
There are 0 directories and 250 images in 'pizza_steak/test/steak'.
There are 0 directories and 250 images in 'pizza_steak/test/pizza'.


In [ ]:
#lets build

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
 

tf.random.set_seed(42)
generalisedTrainData = ImageDataGenerator(rescale=1./255)
genaeralisedValidData =  ImageDataGenerator(rescale=1./255)

In [ ]:
traindir="/content/pizza_steak/train"
testdir="/content/pizza_steak/test"

In [ ]:
traindata=generalisedTrainData.flow_from_directory(directory=traindir,
                                                    batch_size=32,
                                                    target_size=(224,224),
                                                    class_mode="binary",
                                                    seed=42)

Found 1500 images belonging to 2 classes.


In [ ]:
validdata=genaeralisedValidData.flow_from_directory(directory=testdir,
                                                    batch_size=32,
                                                    target_size=(224,224),
                                                    seed=42
                                                    )

Found 500 images belonging to 2 classes.


In [ ]:
model1=tf.keras.Sequential([
    tf.keras.layers.Conv2D(filters=10,
                           kernel_size=3,
                           activation="relu",
                           input_shape=(224,224,3)),
    tf.keras.layers.Conv2D(10,3, activation="relu"),
    tf.keras.layers.MaxPool2D(pool_size=2,
                              padding="valid"),
    tf.keras.layers.Conv2D(10,3,activation ="relu"),
    tf.keras.layers.Conv2D(10,3, activation="relu"),
    tf.keras.layers.MaxPool2D(2
                              ),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1,
                          activation="sigmoid")
])

In [ ]:
model1.compile(
    loss=tf.keras.losses.binary_crossentropy,
    optimizer=tf.keras.optimizers.Adam(),
    metrics = ["accuracy"]
)

In [ ]:
history1=model1.fit(traindata,
                    epochs=5,
                    steps_per_epoch=len(traindata),
                    validation_data=validdata,
                    validation_steps=len(validdata))

Epoch 1/5
47/47 [==============================] - 13s 270ms/step - loss: 0.5663 - accuracy: 0.7120 - val_loss: 1.1554 - val_accuracy: 0.5000
Epoch 2/5
47/47 [==============================] - 11s 236ms/step - loss: 0.4383 - accuracy: 0.8067 - val_loss: 1.1593 - val_accuracy: 0.5000
Epoch 3/5
47/47 [==============================] - 11s 235ms/step - loss: 0.4190 - accuracy: 0.8160 - val_loss: 1.0277 - val_accuracy: 0.5000
Epoch 4/5
47/47 [==============================] - 11s 238ms/step - loss: 0.3688 - accuracy: 0.8413 - val_loss: 1.1564 - val_accuracy: 0.5000
Epoch 5/5
47/47 [==============================] - 12s 248ms/step - loss: 0.3246 - accuracy: 0.8647 - val_loss: 1.4123 - val_accuracy: 0.5000


In [ ]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 222, 222, 10)      280       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 220, 220, 10)      910       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 110, 110, 10)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 108, 108, 10)      910       
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 106, 106, 10)      910       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 53, 53, 10)        0         
_________________________________________________________________
flatten (Flatten)            (None, 28090)             0

In [ ]:
tf.random.set_seed(42)

In [ ]:
model2=tf.keras.Sequential([
                                   tf.keras.layers.Dense(4, activation="relu"),
                                   tf.keras.layers.Dense(4, activation="relu"),
                                   tf.keras.layers.Dense(1, activation = "sigmoid")
])

model2.compile(loss = tf.keras.losses.binary_crossentropy,
           optimizer= tf.keras.optimizers.Adam(),
           metrics = ["accuracy"])

In [ ]:
history2=model1.fit(traindata,
                    epochs=5,
                    steps_per_epoch=len(traindata),
                    validation_data=validdata,
                    validation_steps=len(validdata))

Epoch 1/5
47/47 [==============================] - 12s 255ms/step - loss: 0.2864 - accuracy: 0.8860 - val_loss: 1.6780 - val_accuracy: 0.5000
Epoch 2/5
47/47 [==============================] - 12s 254ms/step - loss: 0.2079 - accuracy: 0.9260 - val_loss: 1.9681 - val_accuracy: 0.5000
Epoch 3/5
47/47 [==============================] - 12s 251ms/step - loss: 0.1678 - accuracy: 0.9440 - val_loss: 1.9136 - val_accuracy: 0.5000
Epoch 4/5
47/47 [==============================] - 12s 252ms/step - loss: 0.0945 - accuracy: 0.9713 - val_loss: 2.2541 - val_accuracy: 0.5000
Epoch 5/5
47/47 [==============================] - 12s 247ms/step - loss: 0.0586 - accuracy: 0.9847 - val_loss: 2.7132 - val_accuracy: 0.5000


In [ ]:
import zipfile

!wget https://storage.googleapis.com/ztm_tf_course/food_vision/10_food_classes_all_data.zip

--2021-10-28 04:36:04--  https://storage.googleapis.com/ztm_tf_course/food_vision/10_food_classes_all_data.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.132.128, 74.125.202.128, 74.125.69.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.132.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 519183241 (495M) [application/zip]
Saving to: ‘10_food_classes_all_data.zip’

10_food_classes_all 100%[===================>] 495.13M   164MB/s    in 3.0s    

2021-10-28 04:36:08 (164 MB/s) - ‘10_food_classes_all_data.zip’ saved [519183241/519183241]



In [ ]:
zip_ref=zipfile.ZipFile("10_food_classes_all_data.zip")
zip_ref.extractall()
zip_ref.close()

In [ ]:
import os 
for dirpath, dirnames, filenames in os.walk("10_food_classes_all_data"):
  print(f"There are {len(dirnames)} directories and {len(filenames)} images in '{dirpath}'.")
  

There are 2 directories and 0 images in '10_food_classes_all_data'.
There are 10 directories and 0 images in '10_food_classes_all_data/train'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/pizza'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/chicken_wings'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/ice_cream'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/fried_rice'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/steak'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/ramen'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/hamburger'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/sushi'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/grilled_salmon'.
There are 0 directories and 750 images in '10_food_classes_all_data/train/chicken_curry'.

In [ ]:
train_dir="10_food_classes_all_data/train/"
test_dir="10_food_classes_all_data/test/"

In [ ]:
import pathlib
import numpy as np
data_dir = pathlib.Path(train_dir)
class_names = np.array(sorted([item.name for item in data_dir.glob('*')]))
print(class_names)

['chicken_curry' 'chicken_wings' 'fried_rice' 'grilled_salmon' 'hamburger'
 'ice_cream' 'pizza' 'ramen' 'steak' 'sushi']


In [ ]:
# View a random image from the training dataset
import random
img = view_random(target_dir=train_dir,
                        target_class=random.choice(class_names))

NameError: ignored

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Rescale the data and create data generator instances
train_datagen = ImageDataGenerator(rescale=1/255.)
test_datagen = ImageDataGenerator(rescale=1/255.)

# Load data in from directories and turn it into batches
train_data = train_datagen.flow_from_directory(train_dir,
                                               target_size=(224, 224),
                                               batch_size=32,
                                               class_mode='categorical') # changed to categorical

test_data = train_datagen.flow_from_directory(test_dir,
                                              target_size=(224, 224),
                                              batch_size=32,
                                              class_mode='categorical')

Found 7500 images belonging to 10 classes.
Found 2500 images belonging to 10 classes.


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Dense, Flatten


In [ ]:

# Create our model (a clone of model_8, except to be multi-class)
model_9 = Sequential([
  Conv2D(10, 3, activation='relu', input_shape=(224, 224, 3)),
  Conv2D(10, 3, activation='relu'),
  MaxPool2D(),
  Conv2D(10, 3, activation='relu'),
  Conv2D(10, 3, activation='relu'),
  MaxPool2D(),
  Flatten(),
  Dense(10, activation='softmax') # changed to have 10 neurons (same as number of classes) and 'softmax' activation
])

# Compile the model
model_9.compile(loss="categorical_crossentropy", # changed to categorical_crossentropy
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [ ]:
# Fit the model
history_9 = model_9.fit(train_data, # now 10 different classes 
                        epochs=5,
                        steps_per_epoch=len(train_data),
                        validation_data=test_data,
                        validation_steps=len(test_data))

Epoch 1/5
235/235 [==============================] - 83s 221ms/step - loss: 2.1379 - accuracy: 0.2125 - val_loss: 2.0071 - val_accuracy: 0.2960
Epoch 2/5
235/235 [==============================] - 53s 225ms/step - loss: 1.8902 - accuracy: 0.3412 - val_loss: 1.7930 - val_accuracy: 0.3808
Epoch 3/5
235/235 [==============================] - 54s 232ms/step - loss: 1.6324 - accuracy: 0.4499 - val_loss: 1.7599 - val_accuracy: 0.3852
Epoch 4/5
235/235 [==============================] - 54s 228ms/step - loss: 1.2869 - accuracy: 0.5765 - val_loss: 1.9671 - val_accuracy: 0.3680
Epoch 5/5
235/235 [==============================] - 53s 225ms/step - loss: 0.7758 - accuracy: 0.7508 - val_loss: 2.4208 - val_accuracy: 0.3224


Transfer learning


In [ ]:
!nvidia-smi

Fri Oct 29 06:27:09 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8    33W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import zipfile
!wget https://storage.googleapis.com/ztm_tf_course/food_vision/10_food_classes_10_percent.zip

--2021-10-29 06:27:11--  https://storage.googleapis.com/ztm_tf_course/food_vision/10_food_classes_10_percent.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 173.194.192.128, 209.85.145.128, 172.217.219.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|173.194.192.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 168546183 (161M) [application/zip]
Saving to: ‘10_food_classes_10_percent.zip’

10_food_classes_10_ 100%[===================>] 160.74M   119MB/s    in 1.3s    

2021-10-29 06:27:12 (119 MB/s) - ‘10_food_classes_10_percent.zip’ saved [168546183/168546183]



In [ ]:
zip_ref=zipfile.ZipFile("10_food_classes_10_percent.zip", "r")
zip_ref.extractall()
zip_ref.close()

In [ ]:
import os
for dirpath, dirnames, filenames in os.walk("10_food_classes_10_percent"):
  print(f"There are {len(dirnames)} directories and {len(filenames)} images in '{dirpath}'.")

There are 2 directories and 0 images in '10_food_classes_10_percent'.
There are 10 directories and 0 images in '10_food_classes_10_percent/train'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/fried_rice'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/grilled_salmon'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/chicken_wings'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/hamburger'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/pizza'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/ice_cream'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/ramen'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/steak'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/sushi'.
There are 0 directories and 75 images in '10_food_classes_10_percent/train/c

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
IMAGE_SHAPE = (224, 224)
BATCH_SIZE = 32

train_dir = "10_food_classes_10_percent/train/"
test_dir = "10_food_classes_10_percent/test/"

train_datagen = ImageDataGenerator(rescale=1/255.)
test_datagen = ImageDataGenerator(rescale=1/255.)

print("Training images:")
train_data_10_percent = train_datagen.flow_from_directory(train_dir,
                                               target_size=IMAGE_SHAPE,
                                               batch_size=BATCH_SIZE,
                                               class_mode="categorical")

print("Testing images:")
test_data = train_datagen.flow_from_directory(test_dir,
                                              target_size=IMAGE_SHAPE,
                                              batch_size=BATCH_SIZE,
                                              class_mode="categorical")

Training images:
Found 750 images belonging to 10 classes.
Testing images:
Found 2500 images belonging to 10 classes.


In [ ]:
#SETTING THE CALLBACK
import datetime

def create_tensorboard_callback(dir_name, experiment_name):
  log_dir = dir_name + "/" + experiment_name + "/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
  tensorboard_callback = tf.keras.callbacks.TensorBoard(
      log_dir=log_dir
  )
  print(f"Saving TensorBoard log files to: {log_dir}")
  return tensorboard_callback

In [ ]:
comparing two models

In [ ]:
# Resnet 50 V2 feature vector
resnet_url = "https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/4"

# Original: EfficientNetB0 feature vector (version 1)
efficientnet_url = "https://tfhub.dev/tensorflow/efficientnet/b0/feature-vector/1"

# # New: EfficientNetB0 feature vector (version 2)
# efficientnet_url = "https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet1k_b0/feature_vector/2" 